/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.generator_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param mediaUrl 
 * @param width 
 * @param placementFormatRatio 
 * @param id 
 * @param height 
 */


data class UpsertCreativeDto (

    @Json(name = "mediaUrl")
    val mediaUrl: kotlin.String,

    @Json(name = "width")
    val width: java.math.BigDecimal? = null,

    @Json(name = "placementFormatRatio")
    val placementFormatRatio: kotlin.String? = null,

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "height")
    val height: java.math.BigDecimal? = null

)

