/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.Banner
import ai.corca.adcio_placement.model.Campaign
import ai.corca.adcio_placement.model.Placement
import ai.corca.adcio_placement.model.Product

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param placement 
 * @param placementId 
 * @param maxBudgetPerDay 
 * @param totalBudgetInPeriod 
 * @param budgetType 
 * @param usedBudget 
 * @param activated 
 * @param products 
 * @param banners 
 * @param startsAt 
 * @param endsAt 
 * @param campaign 
 * @param campaignId 
 * @param createdAt 
 * @param updatedAt 
 * @param deletedAt 
 */


data class AdGroup (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "placement")
    val placement: Placement,

    @Json(name = "placementId")
    val placementId: kotlin.String,

    @Json(name = "maxBudgetPerDay")
    val maxBudgetPerDay: java.math.BigDecimal,

    @Json(name = "totalBudgetInPeriod")
    val totalBudgetInPeriod: java.math.BigDecimal?,

    @Json(name = "budgetType")
    val budgetType: AdGroup.BudgetType,

    @Json(name = "usedBudget")
    val usedBudget: java.math.BigDecimal,

    @Json(name = "activated")
    val activated: kotlin.Boolean,

    @Json(name = "products")
    val products: kotlin.collections.List<Product>,

    @Json(name = "banners")
    val banners: kotlin.collections.List<Banner>,

    @Json(name = "startsAt")
    val startsAt: java.time.OffsetDateTime,

    @Json(name = "endsAt")
    val endsAt: java.time.OffsetDateTime?,

    @Json(name = "campaign")
    val campaign: Campaign,

    @Json(name = "campaignId")
    val campaignId: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime?

) {

    /**
     * 
     *
     * Values: dAILYBUDGET,tOTALBUDGETINPERIOD,mAXBUDGETPERDAY
     */
    @JsonClass(generateAdapter = false)
    enum class BudgetType(val value: kotlin.String) {
        @Json(name = "DAILY_BUDGET") dAILYBUDGET("DAILY_BUDGET"),
        @Json(name = "TOTAL_BUDGET_IN_PERIOD") tOTALBUDGETINPERIOD("TOTAL_BUDGET_IN_PERIOD"),
        @Json(name = "MAX_BUDGET_PER_DAY") mAXBUDGETPERDAY("MAX_BUDGET_PER_DAY");
    }
}

