/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param age 
 * @param gender 
 * @param area 
 * @param regularCustomer 
 * @param campaignId 
 * @param createdAt 
 * @param updatedAt 
 */


data class Audience (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "age")
    val age: kotlin.collections.List<Audience.Age>,

    @Json(name = "gender")
    val gender: kotlin.collections.List<Audience.Gender>,

    @Json(name = "area")
    val area: kotlin.collections.List<Audience.Area>,

    @Json(name = "regularCustomer")
    val regularCustomer: kotlin.collections.List<Audience.RegularCustomer>,

    @Json(name = "campaignId")
    val campaignId: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

) {

    /**
     * 
     *
     * Values: _10,_20,_30,_40
     */
    @JsonClass(generateAdapter = false)
    enum class Age(val value: kotlin.String) {
        @Json(name = "10") _10("10"),
        @Json(name = "20") _20("20"),
        @Json(name = "30") _30("30"),
        @Json(name = "40") _40("40");
    }
    /**
     * 
     *
     * Values: male,female
     */
    @JsonClass(generateAdapter = false)
    enum class Gender(val value: kotlin.String) {
        @Json(name = "male") male("male"),
        @Json(name = "female") female("female");
    }
    /**
     * 
     *
     * Values: northernVietnam,southernVietnam
     */
    @JsonClass(generateAdapter = false)
    enum class Area(val value: kotlin.String) {
        @Json(name = "NorthernVietnam") northernVietnam("NorthernVietnam"),
        @Json(name = "SouthernVietnam") southernVietnam("SouthernVietnam");
    }
    /**
     * 
     *
     * Values: _1,_3
     */
    @JsonClass(generateAdapter = false)
    enum class RegularCustomer(val value: kotlin.String) {
        @Json(name = "1") _1("1"),
        @Json(name = "3") _3("3");
    }
}

