/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.Client
import ai.corca.adcio_placement.model.CreditHistory

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param store 
 * @param storeId 
 * @param seller 
 * @param sellerId 
 * @param amount 
 * @param requestedAt 
 * @param reason 
 * @param rejectionReason 
 * @param status 
 * @param processedAt 
 * @param creditHistory 
 */


data class CreditDecreaseRequest (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "store")
    val store: Client,

    @Json(name = "storeId")
    val storeId: kotlin.String,

    @Json(name = "seller")
    val seller: Client,

    @Json(name = "sellerId")
    val sellerId: kotlin.String,

    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    @Json(name = "requestedAt")
    val requestedAt: java.time.OffsetDateTime,

    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "rejectionReason")
    val rejectionReason: kotlin.String?,

    @Json(name = "status")
    val status: CreditDecreaseRequest.Status,

    @Json(name = "processedAt")
    val processedAt: java.time.OffsetDateTime?,

    @Json(name = "creditHistory")
    val creditHistory: CreditHistory?

) {

    /**
     * 
     *
     * Values: pENDING,aPPROVED,rEJECTED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "PENDING") pENDING("PENDING"),
        @Json(name = "APPROVED") aPPROVED("APPROVED"),
        @Json(name = "REJECTED") rEJECTED("REJECTED");
    }
}

