/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.Client
import ai.corca.adcio_placement.model.CreditDecreaseRequest
import ai.corca.adcio_placement.model.Transaction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param store 
 * @param storeId 
 * @param seller 
 * @param sellerId 
 * @param creditType 
 * @param adjustmentType 
 * @param amount 
 * @param createdAt 
 * @param transaction 
 * @param creditDecreaseRequest 
 */


data class CreditHistory (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "store")
    val store: Client?,

    @Json(name = "storeId")
    val storeId: kotlin.String?,

    @Json(name = "seller")
    val seller: Client?,

    @Json(name = "sellerId")
    val sellerId: kotlin.String?,

    @Json(name = "creditType")
    val creditType: kotlin.Any,

    @Json(name = "adjustmentType")
    val adjustmentType: CreditHistory.AdjustmentType,

    @Json(name = "amount")
    val amount: java.math.BigDecimal,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "transaction")
    val transaction: Transaction?,

    @Json(name = "creditDecreaseRequest")
    val creditDecreaseRequest: CreditDecreaseRequest?

) {

    /**
     * 
     *
     * Values: iNCREASE,dECREASE
     */
    @JsonClass(generateAdapter = false)
    enum class AdjustmentType(val value: kotlin.String) {
        @Json(name = "INCREASE") iNCREASE("INCREASE"),
        @Json(name = "DECREASE") dECREASE("DECREASE");
    }
}

