/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param vbankCode 
 * @param vbankDate 
 * @param vbankHolder 
 * @param vbankIssuedAt 
 * @param vbankName 
 * @param vbankNum 
 */


data class IamportPaymentVBank (

    @Json(name = "vbank_code")
    val vbankCode: kotlin.String,

    @Json(name = "vbank_date")
    val vbankDate: java.math.BigDecimal,

    @Json(name = "vbank_holder")
    val vbankHolder: kotlin.String,

    @Json(name = "vbank_issued_at")
    val vbankIssuedAt: java.math.BigDecimal,

    @Json(name = "vbank_name")
    val vbankName: kotlin.String,

    @Json(name = "vbank_num")
    val vbankNum: kotlin.String

)

