/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestId 
 * @param adsetId 
 */


data class LogOptionsDto (

    @Json(name = "requestId")
    val requestId: kotlin.String,

    @Json(name = "adsetId")
    val adsetId: kotlin.String

)

