/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param impressedClassName 
 * @param wrapper 
 */


data class Observer (

    @Json(name = "impressedClassName")
    val impressedClassName: kotlin.String? = null,

    @Json(name = "wrapper")
    val wrapper: kotlin.String? = null

)

