/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.Creative
import ai.corca.adcio_placement.model.Placement

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ratio 
 * @param creatives 
 * @param placements 
 */


data class PlacementFormat (

    @Json(name = "ratio")
    val ratio: kotlin.String,

    @Json(name = "creatives")
    val creatives: kotlin.collections.List<Creative>,

    @Json(name = "placements")
    val placements: kotlin.collections.List<Placement>

)

