/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param removed 
 * @param placementDeactivated 
 */


data class RemoveProductFromPlacementResponseDto (

    @Json(name = "removed")
    val removed: kotlin.Boolean,

    @Json(name = "placementDeactivated")
    val placementDeactivated: kotlin.Boolean

)

