/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cardCompany 
 * @param cardNumber 
 */


data class TransactionPaymentCard (

    @Json(name = "cardCompany")
    val cardCompany: kotlin.String,

    @Json(name = "cardNumber")
    val cardNumber: kotlin.String

)

