/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.BannerWithCreativeDto
import ai.corca.adcio_placement.model.LogOptionsDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param banner 
 * @param logOptions 
 */


data class BannerSuggestionDto (

    @Json(name = "banner")
    val banner: BannerWithCreativeDto,

    @Json(name = "logOptions")
    val logOptions: LogOptionsDto

)

