/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param currency 
 * @param timezone 
 * @param credit 
 * @param paidCredit 
 * @param freeCredit 
 * @param type 
 * @param deletedAt 
 * @param paymentCardId 
 * @param storeId 
 * @param businessLicenseId 
 * @param isSeller 
 * @param createdAt 
 */


data class Client (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "currency")
    val currency: Client.Currency,

    @Json(name = "timezone")
    val timezone: Client.Timezone,

    @Json(name = "credit")
    val credit: java.math.BigDecimal,

    @Json(name = "paidCredit")
    val paidCredit: java.math.BigDecimal,

    @Json(name = "freeCredit")
    val freeCredit: java.math.BigDecimal,

    @Json(name = "type")
    val type: Client.Type,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime?,

    @Json(name = "paymentCardId")
    val paymentCardId: kotlin.String?,

    @Json(name = "storeId")
    val storeId: kotlin.String?,

    @Json(name = "businessLicenseId")
    val businessLicenseId: kotlin.String?,

    @Json(name = "isSeller")
    val isSeller: kotlin.Boolean,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime

) {

    /**
     * 
     *
     * Values: kRW,uSD,vND
     */
    @JsonClass(generateAdapter = false)
    enum class Currency(val value: kotlin.String) {
        @Json(name = "KRW") kRW("KRW"),
        @Json(name = "USD") uSD("USD"),
        @Json(name = "VND") vND("VND");
    }
    /**
     * 
     *
     * Values: kST,iCT,eST,cST,mST,pST,aKST,hST
     */
    @JsonClass(generateAdapter = false)
    enum class Timezone(val value: kotlin.String) {
        @Json(name = "KST") kST("KST"),
        @Json(name = "ICT") iCT("ICT"),
        @Json(name = "EST") eST("EST"),
        @Json(name = "CST") cST("CST"),
        @Json(name = "MST") mST("MST"),
        @Json(name = "PST") pST("PST"),
        @Json(name = "AKST") aKST("AKST"),
        @Json(name = "HST") hST("HST");
    }
    /**
     * 
     *
     * Values: pLATFORMANDSELLER,oWNWEBSITEANDSELLER,pLATFORM,oWNWEBSITE,sELLER,aDMIN
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "PLATFORM_AND_SELLER") pLATFORMANDSELLER("PLATFORM_AND_SELLER"),
        @Json(name = "OWN_WEBSITE_AND_SELLER") oWNWEBSITEANDSELLER("OWN_WEBSITE_AND_SELLER"),
        @Json(name = "PLATFORM") pLATFORM("PLATFORM"),
        @Json(name = "OWN_WEBSITE") oWNWEBSITE("OWN_WEBSITE"),
        @Json(name = "SELLER") sELLER("SELLER"),
        @Json(name = "ADMIN") aDMIN("ADMIN");
    }
}

