/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.AppendInjector
import ai.corca.adcio_placement.model.BannerInjector
import ai.corca.adcio_placement.model.GridInjector
import ai.corca.adcio_placement.model.ImpressionObserver
import ai.corca.adcio_placement.model.Observer
import ai.corca.adcio_placement.model.Retriever
import ai.corca.adcio_placement.model.WidgetInjector

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param retriever 
 * @param impressionObserver 
 * @param observer 
 * @param grid 
 * @param banner 
 * @param append 
 * @param widget 
 */


data class Injector (

    @Json(name = "retriever")
    val retriever: Retriever? = null,

    @Json(name = "impressionObserver")
    val impressionObserver: ImpressionObserver? = null,

    @Json(name = "observer")
    val observer: Observer? = null,

    @Json(name = "grid")
    val grid: GridInjector? = null,

    @Json(name = "banner")
    val banner: BannerInjector? = null,

    @Json(name = "append")
    val append: AppendInjector? = null,

    @Json(name = "widget")
    val widget: WidgetInjector? = null

)

