/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.FetchManyPlacementsResponseDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param count 
 * @param items 
 */


data class PlacementControllerFetchMany200Response (

    @Json(name = "count")
    val count: java.math.BigDecimal? = null,

    @Json(name = "items")
    val items: kotlin.collections.List<FetchManyPlacementsResponseDto>? = null

)

