/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param equalTo 
 * @param not 
 * @param contains 
 */


data class ProductFilterOperationDto (

    @Json(name = "equalTo")
    val equalTo: kotlin.Any? = null,

    @Json(name = "not")
    val not: kotlin.Any? = null,

    @Json(name = "contains")
    val contains: kotlin.String? = null

)

