/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model

import ai.corca.adcio_placement.model.ProductSuggestionDto
import ai.corca.adcio_placement.model.SuggestionResponsePlacementType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param suggestions 
 * @param placement 
 * @param metadata 
 */


data class ProductSuggestionResponseDto (

    @Json(name = "suggestions")
    val suggestions: kotlin.collections.List<ProductSuggestionDto>,

    @Json(name = "placement")
    val placement: SuggestionResponsePlacementType,

    @Json(name = "metadata")
    val metadata: kotlin.Any
)

