/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.adcio_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param image 
 * @param placementType 
 * @param columnSchema 
 * @param uiSchema 
 */


data class Widget (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "image")
    val image: kotlin.String,

    @Json(name = "placementType")
    val placementType: Widget.PlacementType,

    @Json(name = "columnSchema")
    val columnSchema: kotlin.Any,

    @Json(name = "uiSchema")
    val uiSchema: kotlin.Any

) {

    /**
     * 
     *
     * Values: gRID,bANNER
     */
    @JsonClass(generateAdapter = false)
    enum class PlacementType(val value: kotlin.String) {
        @Json(name = "GRID") gRID("GRID"),
        @Json(name = "BANNER") bANNER("BANNER");
    }
}

