/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model

import ai.corca.placement.model.UpsertCreativeDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param `data` 
 * @param deepLink 
 * @param productId 
 * @param name 
 * @param creatives 
 * @param startsAt 
 * @param placementIds 
 * @param appRoute 
 * @param categoryId 
 * @param activated 
 * @param endsAt 
 * @param url 
 */


data class UpdateBannerDto (

    @Json(name = "data")
    val `data`: kotlin.Any,

    @Json(name = "deepLink")
    val deepLink: kotlin.String?,

    @Json(name = "productId")
    val productId: kotlin.String?,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "creatives")
    val creatives: kotlin.collections.List<UpsertCreativeDto>,

    @Json(name = "startsAt")
    val startsAt: java.time.OffsetDateTime,

    @Json(name = "placementIds")
    val placementIds: kotlin.collections.List<kotlin.String>,

    @Json(name = "appRoute")
    val appRoute: kotlin.String?,

    @Json(name = "categoryId")
    val categoryId: kotlin.String?,

    @Json(name = "activated")
    val activated: kotlin.Boolean,

    @Json(name = "endsAt")
    val endsAt: java.time.OffsetDateTime? = null,

    @Json(name = "url")
    val url: kotlin.String? = null

)

