/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param productDetailDataColumns 
 * @param maxDisplayCount 
 * @param displayCount 
 * @param tableSize 
 * @param displayPositions 
 * @param minDisplayCount 
 * @param title 
 * @param activated 
 */


data class UpdatePlacementDto (

    @Json(name = "productDetailDataColumns")
    val productDetailDataColumns: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "maxDisplayCount")
    val maxDisplayCount: java.math.BigDecimal? = null,

    @Json(name = "displayCount")
    val displayCount: java.math.BigDecimal? = null,

    @Json(name = "tableSize")
    val tableSize: kotlin.collections.List<java.math.BigDecimal>? = null,

    @Json(name = "displayPositions")
    val displayPositions: kotlin.collections.List<java.math.BigDecimal>? = null,

    @Json(name = "minDisplayCount")
    val minDisplayCount: java.math.BigDecimal? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "activated")
    val activated: kotlin.Boolean? = null

)

