/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.generator_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param wrapper 
 * @param waitFor 
 * @param template 
 * @param videoTemplate 
 * @param imageTemplate 
 */


data class AppendInjector (

    @Json(name = "wrapper")
    val wrapper: kotlin.String,

    @Json(name = "waitFor")
    val waitFor: kotlin.String,

    @Json(name = "template")
    val template: kotlin.String? = null,

    @Json(name = "videoTemplate")
    val videoTemplate: kotlin.String? = null,

    @Json(name = "imageTemplate")
    val imageTemplate: kotlin.String? = null

)

