/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.generator_placement.model

import ai.corca.generator_placement.model.SuggestionRequestTarget

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param placementId Identifier for the placement which the suggestion will be placed.
 * @param sessionId The session starts when the customer visits the store. It persists until the customer closes the tab, browser or app.
 * @param deviceId The device identifier should be unique for each device. A customer can have multiple devices.
 * @param placementPositionY The Y coordinate of the placement in pixel.
 * @param placementPositionX The X coordinate of the placement in pixel.
 * @param customerId The customer identifier which is generated and managed by the store. The store should configure `frontApi` parameter of ADCIO SDK so that the `customerId` can be sent to ADCIO API.
 * @param fromAgent Whether the request is from the ADCIO agent or not. Default value is `false`.
 * @param sdkVersion The version of the SDK
 * @param userAgent 
 * @param targets 
 */


data class BannerSuggestionRequestDto (

    /* Identifier for the placement which the suggestion will be placed. */
    @Json(name = "placementId")
    val placementId: kotlin.String,

    /* The session starts when the customer visits the store. It persists until the customer closes the tab, browser or app. */
    @Json(name = "sessionId")
    val sessionId: kotlin.String,

    /* The device identifier should be unique for each device. A customer can have multiple devices. */
    @Json(name = "deviceId")
    val deviceId: kotlin.String,

    /* The Y coordinate of the placement in pixel. */
    @Json(name = "placementPositionY")
    val placementPositionY: java.math.BigDecimal? = null,

    /* The X coordinate of the placement in pixel. */
    @Json(name = "placementPositionX")
    val placementPositionX: java.math.BigDecimal? = null,

    /* The customer identifier which is generated and managed by the store. The store should configure `frontApi` parameter of ADCIO SDK so that the `customerId` can be sent to ADCIO API. */
    @Json(name = "customerId")
    val customerId: kotlin.String? = null,

    /* Whether the request is from the ADCIO agent or not. Default value is `false`. */
    @Json(name = "fromAgent")
    val fromAgent: kotlin.Boolean? = null,

    /* The version of the SDK */
    @Json(name = "sdkVersion")
    val sdkVersion: kotlin.String? = null,

    @Json(name = "userAgent")
    val userAgent: kotlin.String? = null,

    @Json(name = "targets")
    val targets: kotlin.collections.List<SuggestionRequestTarget>? = null

)

