/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.generator_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param message 
 * @param error 
 * @param statusCode 
 */


data class NestJSErrorSchema (

    @Json(name = "message")
    val message: kotlin.Any,

    @Json(name = "error")
    val error: kotlin.String,

    @Json(name = "statusCode")
    val statusCode: java.math.BigDecimal

)

