/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.generator_placement.model

import ai.corca.generator_placement.model.Client

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param summary 
 * @param seller 
 * @param additionalInformation 
 * @param image 
 * @param decorationImages 
 * @param additionalImages 
 * @param discountPrice 
 * @param caption 
 * @param storeId 
 * @param url 
 * @param createdAt 
 * @param deletedAt 
 * @param sellerId 
 * @param deepLink 
 * @param price 
 * @param idOnStore 
 * @param includeInRecommendation 
 * @param name 
 * @param id 
 * @param updatedAt 
 */


data class ProductWithSeller (

    @Json(name = "summary")
    val summary: kotlin.String,

    @Json(name = "seller")
    val seller: Client,

    @Json(name = "additionalInformation")
    val additionalInformation: kotlin.collections.List<kotlin.Any>?,

    @Json(name = "image")
    val image: kotlin.String,

    @Json(name = "decorationImages")
    val decorationImages: kotlin.collections.List<kotlin.String>?,

    @Json(name = "additionalImages")
    val additionalImages: kotlin.collections.List<kotlin.String>?,

    @Json(name = "discountPrice")
    val discountPrice: java.math.BigDecimal?,

    @Json(name = "caption")
    val caption: kotlin.String?,

    @Json(name = "storeId")
    val storeId: kotlin.String,

    @Json(name = "url")
    val url: kotlin.String?,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime?,

    @Json(name = "sellerId")
    val sellerId: kotlin.String,

    @Json(name = "deepLink")
    val deepLink: kotlin.String?,

    @Json(name = "price")
    val price: java.math.BigDecimal,

    @Json(name = "idOnStore")
    val idOnStore: kotlin.String,

    @Json(name = "includeInRecommendation")
    val includeInRecommendation: kotlin.Boolean,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

)

