/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.generator_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertyValues The value of the target.
 * @param keyName The name of the target.
 */


data class SuggestionRequestTarget (

    /* The value of the target. */
    @Json(name = "values")
    val propertyValues: kotlin.collections.List<kotlin.String>,

    /* The name of the target. */
    @Json(name = "keyName")
    val keyName: kotlin.String

)

