/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.generator_placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param summary 
 * @param image 
 * @param sellerId 
 * @param deepLink 
 * @param price 
 * @param idOnStore 
 * @param includeInRecommendation 
 * @param name 
 * @param caption 
 * @param url 
 */


data class UpdateProductDto (

    @Json(name = "summary")
    val summary: kotlin.String? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "sellerId")
    val sellerId: kotlin.String? = null,

    @Json(name = "deepLink")
    val deepLink: kotlin.String? = null,

    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    @Json(name = "idOnStore")
    val idOnStore: kotlin.String? = null,

    @Json(name = "includeInRecommendation")
    val includeInRecommendation: kotlin.Boolean? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "caption")
    val caption: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null

)

