/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model

import ai.corca.placement.model.AdGroupTargetValue
import ai.corca.placement.model.Client

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param store 
 * @param storeId 
 * @param name 
 * @param label 
 * @param selectValues 
 * @param createdAt 
 * @param deletedAt 
 */


data class AdGroupTargetKey (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "store")
    val store: Client,

    @Json(name = "storeId")
    val storeId: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "label")
    val label: kotlin.String,

    @Json(name = "selectValues")
    val selectValues: kotlin.collections.List<AdGroupTargetValue>,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime

)

