/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model

import ai.corca.placement.model.AdGroup
import ai.corca.placement.model.Client

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param client 
 * @param clientId 
 * @param adGroups 
 * @param clickLookbackWindowDays 
 * @param impressionLookbackWindowDays 
 * @param createdAt 
 * @param updatedAt 
 * @param deletedAt 
 */


data class Campaign (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "client")
    val client: Client,

    @Json(name = "clientId")
    val clientId: kotlin.String,

    @Json(name = "adGroups")
    val adGroups: kotlin.collections.List<AdGroup>,

    @Json(name = "clickLookbackWindowDays")
    val clickLookbackWindowDays: java.math.BigDecimal,

    @Json(name = "impressionLookbackWindowDays")
    val impressionLookbackWindowDays: java.math.BigDecimal?,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime?

)

