/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdAt 
 * @param deletedAt 
 * @param mediaUrl 
 * @param bannerId 
 * @param width 
 * @param placementFormatRatio 
 * @param id 
 * @param height 
 * @param updatedAt 
 */


data class Creative (

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime?,

    @Json(name = "mediaUrl")
    val mediaUrl: kotlin.String,

    @Json(name = "bannerId")
    val bannerId: kotlin.String?,

    @Json(name = "width")
    val width: java.math.BigDecimal?,

    @Json(name = "placementFormatRatio")
    val placementFormatRatio: kotlin.String?,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "height")
    val height: java.math.BigDecimal?,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

)

