/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model

import ai.corca.placement.model.UpsertCreativeDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param type 
 * @param creatives 
 * @param placementIds 
 * @param `data` 
 * @param deepLink 
 * @param appRoute 
 * @param startsAt 
 * @param categoryId 
 * @param productId 
 * @param url 
 * @param endsAt 
 */


data class CreateBannerDto (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "type")
    val type: CreateBannerDto.Type,

    @Json(name = "creatives")
    val creatives: kotlin.collections.List<UpsertCreativeDto>,

    @Json(name = "placementIds")
    val placementIds: kotlin.collections.List<kotlin.String>,

    @Json(name = "data")
    val `data`: kotlin.Any,

    @Json(name = "deepLink")
    val deepLink: kotlin.String?,

    @Json(name = "appRoute")
    val appRoute: kotlin.String?,

    @Json(name = "startsAt")
    val startsAt: java.time.OffsetDateTime,

    @Json(name = "categoryId")
    val categoryId: kotlin.String?,

    @Json(name = "productId")
    val productId: kotlin.String?,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "endsAt")
    val endsAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: video,image
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "video") video("video"),
        @Json(name = "image") image("image");
    }
}

