/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model

import ai.corca.placement.model.Creative
import ai.corca.placement.model.Placement

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientId 
 * @param `data` 
 * @param productId 
 * @param creatives 
 * @param placements 
 * @param appRoute 
 * @param type 
 * @param url 
 * @param createdAt 
 * @param deletedAt 
 * @param deepLink 
 * @param name 
 * @param startsAt 
 * @param id 
 * @param endsAt 
 * @param categoryId 
 * @param activated 
 */


data class FetchManyBannersResponseDto (

    @Json(name = "clientId")
    val clientId: kotlin.String,

    @Json(name = "data")
    val `data`: kotlin.Any,

    @Json(name = "productId")
    val productId: kotlin.String?,

    @Json(name = "creatives")
    val creatives: kotlin.collections.List<Creative>,

    @Json(name = "placements")
    val placements: kotlin.collections.List<Placement>,

    @Json(name = "appRoute")
    val appRoute: kotlin.String?,

    @Json(name = "type")
    val type: FetchManyBannersResponseDto.Type,

    @Json(name = "url")
    val url: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "deletedAt")
    val deletedAt: java.time.OffsetDateTime?,

    @Json(name = "deepLink")
    val deepLink: kotlin.String?,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "startsAt")
    val startsAt: java.time.OffsetDateTime,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "endsAt")
    val endsAt: java.time.OffsetDateTime?,

    @Json(name = "categoryId")
    val categoryId: kotlin.String?,

    @Json(name = "activated")
    val activated: kotlin.Boolean

) {

    /**
     * 
     *
     * Values: video,image
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "video") video("video"),
        @Json(name = "image") image("image");
    }
}

