/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param paths 
 * @param template 
 */


data class GridInjector (

    @Json(name = "paths")
    val paths: kotlin.collections.List<kotlin.String>,

    @Json(name = "template")
    val template: kotlin.String

)

