/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param path 
 * @param attribute 
 * @param matcher 
 */


data class Retriever (

    @Json(name = "path")
    val path: kotlin.String,

    @Json(name = "attribute")
    val attribute: kotlin.String,

    @Json(name = "matcher")
    val matcher: Retriever.Matcher? = null

) {

    /**
     * 
     *
     * Values: exact,endsWith,startsWith,contains
     */
    @JsonClass(generateAdapter = false)
    enum class Matcher(val value: kotlin.String) {
        @Json(name = "exact") exact("exact"),
        @Json(name = "endsWith") endsWith("endsWith"),
        @Json(name = "startsWith") startsWith("startsWith"),
        @Json(name = "contains") contains("contains");
    }
}

