/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ai.corca.placement.model

import ai.corca.placement.model.ProductDetailDto

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param summary 
 * @param additionalInformation 
 * @param image 
 * @param decorationImages 
 * @param additionalImages 
 * @param discountPrice 
 * @param caption 
 * @param url 
 * @param sellerId 
 * @param sellerIdOnStore 
 * @param deepLink 
 * @param price 
 * @param idOnStore 
 * @param includeInRecommendation 
 * @param name 
 * @param detail 
 */


data class UpsertProductDto (

    @Json(name = "summary")
    val summary: kotlin.String? = null,

    @Json(name = "additionalInformation")
    val additionalInformation: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "image")
    val image: kotlin.String? = null,

    @Json(name = "decorationImages")
    val decorationImages: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "additionalImages")
    val additionalImages: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "discountPrice")
    val discountPrice: java.math.BigDecimal? = null,

    @Json(name = "caption")
    val caption: kotlin.String? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "sellerId")
    val sellerId: kotlin.String? = null,

    @Json(name = "sellerIdOnStore")
    val sellerIdOnStore: kotlin.String? = null,

    @Json(name = "deepLink")
    val deepLink: kotlin.String? = null,

    @Json(name = "price")
    val price: java.math.BigDecimal? = null,

    @Json(name = "idOnStore")
    val idOnStore: kotlin.String? = null,

    @Json(name = "includeInRecommendation")
    val includeInRecommendation: kotlin.Boolean? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "detail")
    val detail: ProductDetailDto? = null

)

