name: ADCIO Android Plugins CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup MavenLocal and build local-enums
        run: ./gradlew :local-enums:publishToMavenLocal
      - name: Upload local-enums artifact
        uses: actions/upload-artifact@v2
        with:
          name: local-enums
          path: path/to/local-enums/build/output
      - name: Build with Gradle
        run: ./gradlew build
      - name: Download local-enums artifact
        uses: actions/download-artifact@v2
        with:
          name: local-enums
          path: path/where/to/download