name: ADCIO Android Plugins CI
env:
  GRADLE_OPTS: "-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.daemon=false"
  MAVEN_LOCAL_REPO_PATH: /home/runner/.m2/repository

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  publish-local-enums:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Display settings.gradle content
        run: cat settings.gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clear Gradle Cache
        run: ./gradlew build --refresh-dependencies --no-daemon
      - name: Publish local-enums to MavenLocal
        run: |
          ./gradlew :build-logic:local-enums:publishToMavenLocal --info
          echo "Published local-enums to MavenLocal"
      - name: List published artifacts
        run: |
          echo "Listing published artifacts..."
          ls -l ${{ env.MAVEN_LOCAL_REPO_PATH }}/ai/corca/local
      - name: Upload Maven local repository (specific module)
        uses: actions/upload-artifact@v2
        with:
          name: maven-repo-local-enums
          path: ${{ env.MAVEN_LOCAL_REPO_PATH }}/ai/corca/local

  verify-local-enums:
    needs: publish-local-enums
    runs-on: ubuntu-latest
    steps:
      - name: Download Maven local repository (specific module)
        uses: actions/download-artifact@v2
        with:
          name: maven-repo-local-enums
          path: ${{ env.MAVEN_LOCAL_REPO_PATH }}/ai/corca/local
      - name: Verify published artifacts
        run: |
          echo "Verifying published artifacts in MavenLocal..."
          ls -l ${{ env.MAVEN_LOCAL_REPO_PATH }}/ai/corca/local

  build:
    needs: verify-local-enums
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Set Maven local repo path for Gradle
        run: echo "MAVEN_LOCAL_REPO_PATH=${{ env.MAVEN_LOCAL_REPO_PATH }}" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew build -Dmaven.repo.local=${{ env.MAVEN_LOCAL_REPO_PATH }} --info
