name: Dacs

on:
  push:
    branches: [ dacs_test ]
  pull_request:
    branches: [ dacs_test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build dacs module
        run: ./gradlew :dacs:build

      - name: Run tests for dacs module
        run: ./gradlew :dacs:test
